### ISSUE TITLE
Error: Attempt to take the value of the unbound variable `ratify-testing::NIL' during  Quicklisp install

### ISSUE THREAD

**Issue by lbrock** [Shinmera/ratify#3]
Error: Attempt to take the value of the unbound variable `ratify-testing::NIL'.
[condition type: unbound-variable]
With Allegro 10.1SMP ;
Stopped during std quicklisp install 
=====here's the log:
cg-user(74): (ql:quickload "ratify")
To load "ratify":
  Load 4 ASDF systems:
    alexandria asdf cl-ppcre local-time
  Install 2 Quicklisp releases:
    parse-float ratify
; Fetching #<url "http://beta.quicklisp.org/archive/parse-float/2017-10-19/parse-float-20171019-git.tgz">
; 4.59KB
==================================================
4,696 bytes in 0.01 seconds (655.13KB/sec)
; Fetching #<url "http://beta.quicklisp.org/archive/ratify/2018-01-31/ratify-20180131-git.tgz">
; 31.35KB
==================================================
32,107 bytes in 0.07 seconds (461.10KB/sec)
; Loading "ratify"
[package cl-ppcre]................................
..................................................
[package bordeaux-threads]........................
[package cl-fad]..................................
[package path]....................................
[package local-time]..............................
[package parse-float].............................
[package ratify-toolkit]..........................
[package ratify-testing]..........................
[package ratify-parsing]..........................
[package ratify-uri]..............................
[package ratify-url]..............................
[package ratify-email]............................
[package ratify-css]..............................
[package ratify-date].............................
[package ratify-types]............................
[package ratify-html].............................
[package ratify]...
Error: Attempt to take the value of the unbound variable `ratify-testing::NIL'.
[condition type: unbound-variable]
=====here's the backtrace:
![image](https://user-images.githubusercontent.com/406262/41502848-0c42a4f2-7178-11e8-8b72-5028d44aea06.png)

**Comment by Shinmera** [comment]
I don't support Allegro's modern mode, or any non-defualt readtable case.
